modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GENERAL PUBLIC LICENSE"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="epicfight" #mandatory
version="18.5.24" #mandatory
displayName="Epic Fight" #mandatory
#displayURL="https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod" #optional
logoFile="epicfight_logo.png" #optional
#credits="METAL" #optional
#authors="Yesman" #optional
description='''Fight til u dead
'''

[[dependencies.epicfight]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40.2.17,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.epicfight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
